# Generated by Django 2.1.1 on 2018-09-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
