# Generated by Django 2.1.1 on 2018-09-27 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorbike', '0001_initial'),
        ('producers', '0002_auto_20180926_0911'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessory',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='producers.Producer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(null=True, upload_to='photo/accessory')),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accessories.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='require_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='require_for', to='accessories.accessory')),
                ('motorbike_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motobikes', to='motorbike.motorbike')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accessories.accessory')),
                ('sub_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='menus.SubMenu')),
            ],
        ),
    ]
